export const playerActionTypes = {
    SET_N_PLAYERS: 'SET_N_PLAYERS',
    INITIATE_PLAYERS: 'INITIATE_PLAYERS',
    SET_CURRENT_PLAYER: 'SET_CURRENT_PLAYER',
    MOVE_PLAYERS: 'MOVE_PLAYERS',
    MOVE_PLAYERS_SNL: 'MOVE_PLAYERS_SNL'
}